import type { NmapScanData, OWASPCategory } from '../types/electron.d'

interface ReportViewerProps {
  scan: NmapScanData
}

const SEVERITY_COLORS: Record<string, { bg: string; text: string }> = {
  critical: { bg: 'bg-[oklch(0.55_0.22_25)]', text: 'text-white' },
  high: { bg: 'bg-[oklch(0.65_0.25_45)]', text: 'text-black' },
  medium: { bg: 'bg-[oklch(0.70_0.15_85)]', text: 'text-black' },
  low: { bg: 'bg-[oklch(0.55_0.15_150)]', text: 'text-black' },
  info: { bg: 'bg-muted', text: 'text-muted-foreground' },
}

const OWASP_NAMES: Record<string, string> = {
  A01: 'Broken Access Control',
  A02: 'Cryptographic Failures',
  A03: 'Injection',
  A04: 'Insecure Design',
  A05: 'Security Misconfiguration',
  A06: 'Vulnerable Components',
  A07: 'Auth Failures',
  A08: 'Integrity Failures',
  A09: 'Logging Failures',
  A10: 'SSRF',
}

function getGradeColor(grade?: string): string {
  if (!grade) return 'text-muted-foreground'
  if (grade === 'A+' || grade === 'A') return 'text-[oklch(0.55_0.15_150)]'
  if (grade === 'B') return 'text-[oklch(0.70_0.15_85)]'
  if (grade === 'C') return 'text-[oklch(0.65_0.25_45)]'
  return 'text-[oklch(0.55_0.22_25)]'
}

export default function ReportViewer({ scan }: ReportViewerProps) {
  const timestamp = new Date(scan.timestamp).toLocaleString()
  const score = scan.securityScore
  const owasp = scan.owaspCoverage
  const distribution = scan.owaspDistribution

  // Count vulnerabilities by severity
  const severityCounts = {
    critical: scan.vulnerabilities.filter(v => v.severity === 'critical').length,
    high: scan.vulnerabilities.filter(v => v.severity === 'high').length,
    medium: scan.vulnerabilities.filter(v => v.severity === 'medium').length,
    low: scan.vulnerabilities.filter(v => v.severity === 'low').length,
    info: scan.vulnerabilities.filter(v => v.severity === 'info').length,
  }

  // Sort vulnerabilities by severity
  const severityOrder = { critical: 0, high: 1, medium: 2, low: 3, info: 4 }
  const sortedVulns = [...scan.vulnerabilities].sort(
    (a, b) => (severityOrder[a.severity] || 5) - (severityOrder[b.severity] || 5)
  )

  return (
    <div className="p-6 space-y-6 overflow-auto h-full font-mono text-sm">
      {/* Header */}
      <div className="border border-border p-6">
        <h1 className="text-2xl font-bold text-primary mb-4">Security Assessment Report</h1>
        <div className="grid grid-cols-2 gap-2 text-xs">
          <div><span className="text-muted-foreground">Target:</span> {scan.target}</div>
          <div><span className="text-muted-foreground">Scan Type:</span> {scan.scanType}</div>
          <div><span className="text-muted-foreground">Timestamp:</span> {timestamp}</div>
          <div><span className="text-muted-foreground">Generated by:</span> PurpleTeam Suite</div>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="border border-border">
        <div className="border-b border-border px-4 py-2 bg-muted/30">
          <h2 className="text-xs uppercase tracking-wider text-muted-foreground">Executive Summary</h2>
        </div>
        <div className="p-4">
          <div className="grid grid-cols-5 gap-4">
            {(['critical', 'high', 'medium', 'low'] as const).map(sev => (
              <div key={sev} className="text-center p-4 border border-border">
                <div className={`text-3xl font-bold ${SEVERITY_COLORS[sev].bg.replace('bg-', 'text-').replace(']', '/80]')}`}>
                  {severityCounts[sev]}
                </div>
                <div className="text-xs uppercase text-muted-foreground mt-1">{sev}</div>
              </div>
            ))}
            <div className="text-center p-4 border border-border">
              <div className="text-3xl font-bold text-primary">
                {scan.ports.filter(p => p.state === 'open').length}
              </div>
              <div className="text-xs uppercase text-muted-foreground mt-1">Open Ports</div>
            </div>
          </div>
        </div>
      </div>

      {/* Score and OWASP */}
      <div className="grid grid-cols-2 gap-6">
        {/* Security Score */}
        <div className="border border-border">
          <div className="border-b border-border px-4 py-2 bg-muted/30">
            <h2 className="text-xs uppercase tracking-wider text-muted-foreground">Security Score</h2>
          </div>
          <div className="p-6 text-center">
            {score ? (
              <>
                <div className={`text-5xl font-bold ${getGradeColor(score.grade)}`}>
                  {score.overall}%
                </div>
                <div className={`text-2xl font-bold mt-2 ${getGradeColor(score.grade)}`}>
                  Grade: {score.grade}
                </div>
                <div className="mt-4 space-y-2 text-xs text-left">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Severity Impact</span>
                    <span className="text-[oklch(0.55_0.22_25)]">{score.breakdown.severityImpact}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">OWASP Coverage</span>
                    <span className="text-[oklch(0.65_0.25_45)]">{score.breakdown.owaspCoverage}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Remediation Potential</span>
                    <span className="text-primary">{score.breakdown.remediationPotential}</span>
                  </div>
                </div>
              </>
            ) : (
              <div className="text-muted-foreground">No score calculated</div>
            )}
          </div>
        </div>

        {/* OWASP Coverage */}
        <div className="border border-border">
          <div className="border-b border-border px-4 py-2 bg-muted/30">
            <h2 className="text-xs uppercase tracking-wider text-muted-foreground">OWASP Top 10 Coverage</h2>
          </div>
          <div className="p-4">
            <div className="grid grid-cols-5 gap-2">
              {(Object.keys(OWASP_NAMES) as OWASPCategory[]).map(cat => {
                const count = distribution?.[cat] || 0
                const isFound = count > 0
                return (
                  <div
                    key={cat}
                    className={`border p-2 text-center ${
                      isFound ? 'border-primary bg-primary/10' : 'border-border/50'
                    }`}
                    title={OWASP_NAMES[cat]}
                  >
                    <div className={`text-xs font-bold ${isFound ? 'text-primary' : 'text-muted-foreground/40'}`}>
                      {cat}
                    </div>
                    <div className={`text-[10px] ${isFound ? 'text-foreground/60' : 'text-muted-foreground/30'}`}>
                      {OWASP_NAMES[cat]}
                    </div>
                  </div>
                )
              })}
            </div>
            <div className="mt-3 text-xs text-muted-foreground">
              Coverage: {owasp?.total || 0}/10 categories ({owasp?.percentage || 0}%)
            </div>
          </div>
        </div>
      </div>

      {/* Open Ports */}
      <div className="border border-border">
        <div className="border-b border-border px-4 py-2 bg-muted/30">
          <h2 className="text-xs uppercase tracking-wider text-muted-foreground">
            Open Ports ({scan.ports.filter(p => p.state === 'open').length})
          </h2>
        </div>
        <div className="p-4">
          <div className="flex flex-wrap gap-2">
            {scan.ports.filter(p => p.state === 'open').map(p => (
              <div key={`${p.port}-${p.protocol}`} className="px-3 py-1.5 border border-primary/50 text-xs">
                <span className="font-bold text-primary">{p.port}/{p.protocol}</span>
                <span className="text-muted-foreground ml-2">{p.service || 'unknown'}</span>
                {p.version && <span className="text-muted-foreground/60 ml-1">({p.version})</span>}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Vulnerabilities */}
      <div className="border border-border">
        <div className="border-b border-border px-4 py-2 bg-muted/30">
          <h2 className="text-xs uppercase tracking-wider text-muted-foreground">
            Vulnerabilities ({scan.vulnerabilities.length})
          </h2>
        </div>
        <div className="divide-y divide-border">
          {sortedVulns.map(vuln => {
            const analysis = scan.llmAnalysis?.analyses?.find(
              (a: { vulnerabilityId: string }) => a.vulnerabilityId === vuln.id
            )
            const colors = SEVERITY_COLORS[vuln.severity] || SEVERITY_COLORS.info

            return (
              <div key={vuln.id} className="p-4">
                <div className="flex items-start gap-3">
                  <span className={`px-2 py-0.5 text-[10px] uppercase font-bold ${colors.bg} ${colors.text}`}>
                    {vuln.severity}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="font-semibold">{vuln.title}</div>
                    {vuln.cve && (
                      <div className="text-xs text-primary mt-0.5">{vuln.cve}</div>
                    )}
                    <div className="text-xs text-muted-foreground mt-1">
                      {vuln.port && <span>Port {vuln.port}</span>}
                      {vuln.service && <span className="ml-2">• {vuln.service}</span>}
                    </div>
                    <p className="text-xs text-muted-foreground mt-2">{vuln.description}</p>

                    {/* LLM Analysis */}
                    {analysis && (
                      <div className="mt-3 p-3 border-l-2 border-primary bg-primary/5">
                        <div className="text-xs font-semibold text-primary mb-2">AI Analysis</div>
                        <p className="text-xs text-foreground/80">{analysis.plainEnglishSummary}</p>
                        
                        {analysis.remediationSteps?.length > 0 && (
                          <div className="mt-2">
                            <div className="text-[10px] uppercase text-muted-foreground mb-1">Remediation</div>
                            <ul className="text-xs space-y-1">
                              {analysis.remediationSteps.map((step: string, i: number) => (
                                <li key={i} className="text-foreground/70">• {step}</li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {analysis.owaspCategory && (
                          <div className="mt-2 text-[10px]">
                            <span className="text-muted-foreground">OWASP: </span>
                            <span className="text-primary">{analysis.owaspCategory}</span>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-xs text-muted-foreground/60 py-4 border-t border-border">
        Generated by PurpleTeam Suite • {new Date().toLocaleString()}
      </div>
    </div>
  )
}
